# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://dev-ps-loadtest-dummy.pantheonsite.io/")
    self.driver.set_window_size(1024, 700)
    self.driver.find_element(By.CSS_SELECTOR, ".site-logo > img").click()
    element = self.driver.find_element(By.LINK_TEXT, "Articles")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".read-more:nth-child(4) > .read-more__link").click()
    self.driver.execute_script("window.scrollTo(0,318.6666564941406)")
    self.driver.find_element(By.LINK_TEXT, "Edit").click()
    self.driver.find_element(By.LINK_TEXT, "Edit").click()
    element = self.driver.find_element(By.LINK_TEXT, "Edit")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "edit-title-0-value").click()
    self.driver.find_element(By.ID, "edit-title-0-value").send_keys("None his job guess expect. AD")
    self.driver.find_element(By.CSS_SELECTOR, ".layout-region-node-footer").click()
    self.driver.find_element(By.ID, "edit-submit").click()
  
